[package]
name = "cairo_vm_hints"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode.workspace = true
cairo-vm.workspace = true
clap.workspace = true
rand.workspace = true
starknet-types-core.workspace = true
thiserror.workspace = true