name: Main

on: [pull_request, push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          make setup

      - name: Check python formatting
        run: source venv/bin/activate && ./tools/make/python_format_check.sh

      - name: Check cairo Formatting
        run: |
          source venv/bin/activate && ./tools/make/cairo_format_check.sh
      - name: Compile cairo files
        run: source venv/bin/activate && make build

      - name: Run Cairo tests
        env:
          RPC_URL_MAINNET: ${{ secrets.RPC_URL_MAINNET }}
          RPC_URL: ${{ secrets.RPC_URL }}
        run: source ./tools/make/cairo_tests.sh

      - name: Run MPT tests
        run: source ./tools/make/fuzzer.sh tests/fuzzing/mpt.cairo --ci

      - name: Run cairo_vm_hints tests
        run: cargo test
